### ISSUE TITLE
Can't update Nitrokey FIDO2 to 2.2 from 2.1

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-webupdate#15]
My LED never go white (only once if i connect the stick to PC).

here the logs:
![image](https://user-images.githubusercontent.com/9625159/94323059-a794a200-ff94-11ea-8b64-9624f5d91994.png)

failed:
![image](https://user-images.githubusercontent.com/9625159/94323075-b713eb00-ff94-11ea-9317-aa731e142648.png)

I also try pressing it at start but nothing happens. The LED looks also like red & blue at flashing progress.

**Comment by szszszsz** [comment]
Connected https://github.com/Nitrokey/nitrokey-fido2-firmware/issues/57

**Comment by szszszsz** [comment]
@beerisgood @andyrtr 
Could you confirm please that suggestion in https://github.com/Nitrokey/nitrokey-fido2-firmware/issues/57 works for you? (in a forced update mode).

**Comment by andyrtr** [comment]
Yes, I could update my two Fido2 tokens using that long press, Thanks for your help.

**Comment by beerisgood** [comment]
@szszszsz 
I can confirm that this solution works in Microsoft (Chromium-)Edge.

i press the key until the process start and then follow cancelling the first Windows popup from next instructions.

Here also the log:
 
[update.log](https://github.com/Nitrokey/nitrokey-webupdate/files/5294927/update.log)

After browser restart & key replug:
[successfull.log](https://github.com/Nitrokey/nitrokey-webupdate/files/5294930/successfull.log)

So i close this issue as solved and hope your solution get pinned somewhere :)
Thanks also for testing @andyrtr

**Comment by szszszsz** [comment]
Added description regarding the additional popup needed to be cancelled.
Retested on:
- Firefox 81.0.1
- Windows 10 2004

**Comment by beerisgood** [comment]
> Added description regarding the additional popup needed to be cancelled.
> Retested on:
> 
> * Firefox 81.0.1
> * Windows 10 2004

Huh? I test it on Edge so why still not list it ?

**Comment by szszszsz** [comment]
@beerisgood I wanted to run tests separately, so that the service will be opened asap. Will keep in mind to test Edge and other browsers under Windows.
