### ISSUE TITLE
Force update on not supported browser and missing steps in description

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-webupdate#20]
![image](https://user-images.githubusercontent.com/9625159/105495244-39e75100-5cbc-11eb-8ab1-94b185c2489c.png)

where is the expert option to enforce the browser?

Edit: Ups. Found at bottom right.

**Comment by beerisgood** [comment]
> I understand that the part about keeping the touch longer is missing, is that right?

Correct!
or in easier:
after start flashing, hold key button until white light starts blinking (~5 seconds)
on redirected site cancel the first Window popup and wait

**Comment by szszszsz** [comment]
I see. You should have seen the page with image asking to cancel the system popup. If not, then perhaps there is something wrong with the UI update during the process - will check.

Regarding the button long pressing, I have checked current description (image below), and it seems to summarize the action completely, though perhaps not simply enough. Could you suggest changes here?

As for pressing in general, actually user should wait until the LED starts flashing, then press the touch button. I am considering linking to the documentation page regarding touch button / LED behavior guide in the beginning of the process, in case it would create too much confusion.
Mentioned page (please forgive the table graphical state - we are transitioning to new documentation system):
- https://docs.nitrokey.com/fido2/windows/index.html#touch-button-and-led-behavior

Current description for comparison (entry screen, pre-execution of the update process):
![image](https://user-images.githubusercontent.com/17005426/105507138-20013a80-5ccb-11eb-820c-f39ef6b88fd7.png)

**Comment by beerisgood** [comment]
The image was available, but steps weren't easy to understand.

I would add an easier step by step like i wrote in post above. At least the instructions should speak about long pressing key button until next window/ redirected site appears.

**Comment by szszszsz** [comment]
I understand. We will try to redesign the steps here then. Perhaps to be more like a step-by-step wizard for the actual process, instead of executing all at once. That should reduce the required information to be remembered.
Thank you for the feedback!

cc @jans23
