### ISSUE TITLE
Does not work with Linux and Firefox

### ISSUE THREAD

**Issue by rugk** [Nitrokey/nitrokey-webupdate#9]
Env:

> Firefox 78.0 on Fedora 64-bit (WebAuthn supported)
> Connected Nitrokey FIDO2 firmware version: unknown
>Latest Nitrokey FIDO2 firmware version: 2.0.0.nitrokey
>Device state: not available
>
>Update application status: (0) Communication Error 

Console:
```
19:23:09.967 STABLE_VERSION GITHUB 2.0.0.nitrokey main.js:155:11
19:23:10.058 STABLE_VERSION FETCHED 2.0.0.nitrokey main.js:162:11
19:23:13.253 app.solo_version null main.js:257:11
19:23:13.253 PRE-CHECKING IF IN BOOTLOADER main.js:258:11
19:23:17.817 Boot check undefined main.js:349:11
19:23:17.821 Failed running inspection main.js:288:13
```

This is your Nitrokey Fido U2F key.

WebAuthn usually works on websites.
The device does also blink and browser shows me it wants to authenticate etc. And I can tap on the button and confirm that…

**Comment by szszszsz** [comment]
Hi @rugk !
I am sorry but Nitrokey FIDO U2F does not support updates. I will make sure this will be clearly visible in the error message.
